//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид оплаты.
    /// </summary>
    // *** Start programmer edit section *** (ВидОплаты CustomAttributes)

    // *** End programmer edit section *** (ВидОплаты CustomAttributes)
    public enum ВидОплаты
    {
        
        // *** Start programmer edit section *** (ВидОплаты.Наличные CustomAttributes)

        // *** End programmer edit section *** (ВидОплаты.Наличные CustomAttributes)
        [Caption("Наличные")]
        Наличные,
        
        // *** Start programmer edit section *** (ВидОплаты.Карта CustomAttributes)

        // *** End programmer edit section *** (ВидОплаты.Карта CustomAttributes)
        [Caption("Карта")]
        Карта,
    }
}
