//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Категория.
    /// </summary>
    // *** Start programmer edit section *** (Категория CustomAttributes)

    // *** End programmer edit section *** (Категория CustomAttributes)
    public enum Категория
    {
        
        // *** Start programmer edit section *** (Категория.НаДокументы CustomAttributes)

        // *** End programmer edit section *** (Категория.НаДокументы CustomAttributes)
        [Caption("На документы")]
        НаДокументы,
        
        // *** Start programmer edit section *** (Категория.Развлекат CustomAttributes)

        // *** End programmer edit section *** (Категория.Развлекат CustomAttributes)
        [Caption("Развлекательное")]
        Развлекат,
    }
}
