//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отправ на почту.
    /// </summary>
    // *** Start programmer edit section *** (ОтправНаПочту CustomAttributes)

    // *** End programmer edit section *** (ОтправНаПочту CustomAttributes)
    [AutoAltered()]
    [Caption("Отправ на почту")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтправНаПочтуE", new string[] {
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "СделатьФото.Id as \'Сделанное фото\'",
            "СделатьФото.КатегорФото as \'Категория фото\'",
            "СделатьФото.КолВоФото as \'Количество фото\'"})]
    [View("ОтправНаПочтуL", new string[] {
            "ФИО as \'ФИО\'",
            "Email as \'E-mail\'",
            "СделатьФото.Id as \'Сделанное фото\'",
            "СделатьФото.КатегорФото as \'Категория фото\'",
            "СделатьФото.КолВоФото as \'Количество\'"})]
    public class ОтправНаПочту : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fEmail;
        
        private IIS.Fotokiosk9.СделатьФото fСделатьФото;
        
        // *** Start programmer edit section *** (ОтправНаПочту CustomMembers)

        // *** End programmer edit section *** (ОтправНаПочту CustomMembers)

        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (ОтправНаПочту.Email CustomAttributes)

        // *** End programmer edit section *** (ОтправНаПочту.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (ОтправНаПочту.Email Get start)

                // *** End programmer edit section *** (ОтправНаПочту.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (ОтправНаПочту.Email Get end)

                // *** End programmer edit section *** (ОтправНаПочту.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтправНаПочту.Email Set start)

                // *** End programmer edit section *** (ОтправНаПочту.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (ОтправНаПочту.Email Set end)

                // *** End programmer edit section *** (ОтправНаПочту.Email Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (ОтправНаПочту.ФИО CustomAttributes)

        // *** End programmer edit section *** (ОтправНаПочту.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (ОтправНаПочту.ФИО Get start)

                // *** End programmer edit section *** (ОтправНаПочту.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (ОтправНаПочту.ФИО Get end)

                // *** End programmer edit section *** (ОтправНаПочту.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтправНаПочту.ФИО Set start)

                // *** End programmer edit section *** (ОтправНаПочту.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (ОтправНаПочту.ФИО Set end)

                // *** End programmer edit section *** (ОтправНаПочту.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Отправ на почту.
        /// </summary>
        // *** Start programmer edit section *** (ОтправНаПочту.СделатьФото CustomAttributes)

        // *** End programmer edit section *** (ОтправНаПочту.СделатьФото CustomAttributes)
        [PropertyStorage(new string[] {
                "СделатьФото"})]
        [NotNull()]
        public virtual IIS.Fotokiosk9.СделатьФото СделатьФото
        {
            get
            {
                // *** Start programmer edit section *** (ОтправНаПочту.СделатьФото Get start)

                // *** End programmer edit section *** (ОтправНаПочту.СделатьФото Get start)
                IIS.Fotokiosk9.СделатьФото result = this.fСделатьФото;
                // *** Start programmer edit section *** (ОтправНаПочту.СделатьФото Get end)

                // *** End programmer edit section *** (ОтправНаПочту.СделатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтправНаПочту.СделатьФото Set start)

                // *** End programmer edit section *** (ОтправНаПочту.СделатьФото Set start)
                this.fСделатьФото = value;
                // *** Start programmer edit section *** (ОтправНаПочту.СделатьФото Set end)

                // *** End programmer edit section *** (ОтправНаПочту.СделатьФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтправНаПочтуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтправНаПочтуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтправНаПочтуE", typeof(IIS.Fotokiosk9.ОтправНаПочту));
                }
            }
            
            /// <summary>
            /// "ОтправНаПочтуL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтправНаПочтуL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтправНаПочтуL", typeof(IIS.Fotokiosk9.ОтправНаПочту));
                }
            }
        }
    }
}
