//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Печать.
    /// </summary>
    // *** Start programmer edit section *** (Печать CustomAttributes)

    // *** End programmer edit section *** (Печать CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПечатьE", new string[] {
            "СделатьФото.Id as \'Сделанное фото\'",
            "СделатьФото.КатегорФото as \'Категория фото\'",
            "СделатьФото.КолВоФото as \'Количество фото\'",
            "Размер as \'Размер фото\'"})]
    [View("ПечатьL", new string[] {
            "СделатьФото.Id as \'Сделанное фото\'",
            "СделатьФото.КатегорФото as \'Категория фото\'",
            "СделатьФото.КолВоФото as \'Количество фото\'",
            "Размер as \'Размер фото\'"})]
    public class Печать : ICSSoft.STORMNET.DataObject
    {
        
        private string fРазмер;
        
        private IIS.Fotokiosk9.СделатьФото fСделатьФото;
        
        // *** Start programmer edit section *** (Печать CustomMembers)

        // *** End programmer edit section *** (Печать CustomMembers)

        
        /// <summary>
        /// Размер.
        /// </summary>
        // *** Start programmer edit section *** (Печать.Размер CustomAttributes)

        // *** End programmer edit section *** (Печать.Размер CustomAttributes)
        [StrLen(255)]
        public virtual string Размер
        {
            get
            {
                // *** Start programmer edit section *** (Печать.Размер Get start)

                // *** End programmer edit section *** (Печать.Размер Get start)
                string result = this.fРазмер;
                // *** Start programmer edit section *** (Печать.Размер Get end)

                // *** End programmer edit section *** (Печать.Размер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Печать.Размер Set start)

                // *** End programmer edit section *** (Печать.Размер Set start)
                this.fРазмер = value;
                // *** Start programmer edit section *** (Печать.Размер Set end)

                // *** End programmer edit section *** (Печать.Размер Set end)
            }
        }
        
        /// <summary>
        /// Печать.
        /// </summary>
        // *** Start programmer edit section *** (Печать.СделатьФото CustomAttributes)

        // *** End programmer edit section *** (Печать.СделатьФото CustomAttributes)
        [PropertyStorage(new string[] {
                "СделатьФото"})]
        [NotNull()]
        public virtual IIS.Fotokiosk9.СделатьФото СделатьФото
        {
            get
            {
                // *** Start programmer edit section *** (Печать.СделатьФото Get start)

                // *** End programmer edit section *** (Печать.СделатьФото Get start)
                IIS.Fotokiosk9.СделатьФото result = this.fСделатьФото;
                // *** Start programmer edit section *** (Печать.СделатьФото Get end)

                // *** End programmer edit section *** (Печать.СделатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Печать.СделатьФото Set start)

                // *** End programmer edit section *** (Печать.СделатьФото Set start)
                this.fСделатьФото = value;
                // *** Start programmer edit section *** (Печать.СделатьФото Set end)

                // *** End programmer edit section *** (Печать.СделатьФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПечатьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьE", typeof(IIS.Fotokiosk9.Печать));
                }
            }
            
            /// <summary>
            /// "ПечатьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьL", typeof(IIS.Fotokiosk9.Печать));
                }
            }
        }
    }
}
